### ISSUE TITLE
mp4 to mkv subs is ass 

### ISSUE THREAD

**Issue by ircopdd** [sarkinios/sarkui#2]
sbtl Can it be output as SRT? Thanks

**Comment by sarkinios** [comment]
Please be more specific.  Are you trying to import/mux .ass subtitle with an mp4 video container? 
For now, importing subtitles with .mp4 container is supported only with .srt subtitles.  
But you can add .ass .vtt .ssa .idx with .mkv container.
You can solve your problem like this:
1) Convert your mp4 to mkv  
2) Load the new mkv to Sarkui
3) Import/Mux the .ass subtitle in this mkv

If you mean to convert .ass or any subtitle filetype to .srt is not implemented yet in Sarkui. Keep an eye for next update

**Comment by ircopdd** [comment]
**my mp4 Inside subtitle is sbtl**

![2022-08-24_230205](https://user-images.githubusercontent.com/3633003/186453350-e64a4623-954f-4dff-ad6b-64397a943abd.png)


**use sarkui Convert mp4 to mkv  
but output mkv Inside subtitle not srt is ass**

![2022-08-24_230223](https://user-images.githubusercontent.com/3633003/186453359-0bd11c7d-4f6f-407e-83ba-174defe71fc2.png)

**Comment by sarkinios** [comment]
ASS is also Timed Text format. There are many Timed Text subtitle types. Have you trying export the subtitles from your original file and check what kind of Timed Text are?

**Comment by sarkinios** [comment]
ffmpeg automaticaly converts timed text mp4 to .ass (also timed text).  I'll consider changing that in the future to convert in mkv with srt . 

Thanks
